### PR TITLE
Add push dashboard

### PR DESCRIPTION
**Pull request by groovecoder**
the `e2e-test/run` will need these environment variables set:
- `DJANGO_DEBUG_TOOLBAR=False`
- `TESTING_SITE` - what domain/site to test
- `TESTING_WEBDRIVER_TIMEOUT` - this defaults to 0 so that the selenium webdriver tests don't run during unit test run
- `TESTING_FXA_ACCOUNT_EMAIL` - pre-existing FxA account email
- `TESTING_FXA_ACCOUNT_PASSWORD` - pre-existing FxA account password

### CODE REVIEW

**Comment by rpappalax** [comment]
@groovecoder everything looks and thanks for the README updates!  just realized i'm going to need to do some setup on our ubuntu-desktop slave so that your tests will run.  We can prob go ahead and merge these in, but i'm thinking there may be a few tweaks so let me see if i can get them running from your branch first.

**Comment by groovecoder** [comment]
Great, thanks @rpappalax. Think we will have something up and going by tomorrow? I've got a couple other issues I can work on today, but this is one of the last few things to do before launching the dashboard.

**Comment by rpappalax** [comment]
@groovecoder, have quite a few irons in the fire the rest of the week, but I'll devote some time to it today.  I'll prob be pinging you for help once I have the Jenkins job in place.

**Comment by rpappalax** [comment]
@groovecoder looks like i've got the install working now on Jenkins. but it looks like manage.py can't find "test_e2e":
  File "/usr/lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'test_e2e'

Did you mean to invoke "test_login"?
https://github.com/mozilla-services/services-test/blob/add-push-dashboard/push-dashboard/e2e-test/run#L7
https://github.com/mozilla-services/push-dev-dashboard/blob/master/dashboard/tests.py#L88

**Comment by groovecoder** [comment]
Oh, I've got a branch with `dashboard/tests/test_e2e.py` in it. Just sent a PR here:

https://github.com/mozilla-services/push-dev-dashboard/pull/211

Should I merge that here first, or can you change the job to use that branch?

**Comment by rpappalax** [comment]
OK, progress! the test kicks off, but I don't think it's testing much in < 0 seconds ;)
Ran 1 test in 0.000s
So we may need to look into that further.  would you have time for a quick vidyo this afternoon?

**Comment by groovecoder** [comment]
It's skipping the test because it needs env vars set. Especiall `TESTING_WEBDRIVER_TIMEOUT` needs to be > 0 to run the tests at all.

**Comment by groovecoder** [comment]
Reminder here: we need `DJANGO_DEBUG_TOOLBAR=False` env var to make the selenium test run.

**Comment by groovecoder** [comment]
Also, stage environment is here: https://pushdevdashboard-default.stage.mozaws.net/en/

**Comment by groovecoder** [comment]
Moment of inspiration on the weekend ... added `-v2` to the test command to get more verbose output.

**Comment by groovecoder** [comment]
@rpappalax - just checking in: let me know ASAP if you need anything from me. I've got some other issues I'm working on, so I won't be working on this unless you ping me about/on it.

**Comment by groovecoder** [comment]
@rpappalax ping here - you may want to retry the tests on jenkins now that it's expanded on the `start-test-e2e` branch.

**Comment by groovecoder** [comment]
@rpappalax when you get a chance, you can try this again with the master branch of code. It has the test_e2e module now. Ping me here or on IRC if you have any questions?

**Comment by rpappalax** [comment]
dashboard no longer maintained.  closing per @groovecoder

**Pull request closed without merging**
