### PR TITLE
re-adding test manifests

### PR DESCRIPTION
**Pull request by rpappalax**
removed loadtest from prod per pdehaan's suggestion.  adding other manifests

### CODE REVIEW

**Comment by rpappalax** [comment]
@sphilp? @pdehaan?

**Comment by pdehaan** [comment]
What is a "loadtest"?

When testing early versions of reading list, I'd routinely throw some light smoke-level loadtests at the prod environment to make sure things were still working in prod after a deploy. Or is that generally part of what a "stackcheck" would do?

**Comment by rpappalax** [comment]
stack-check is basically making sure that a stack is ready to test.  has the right tag been deployed?  is the right instance being routed to urls?  are urls rendering?  are processes up-n-running?  aka: everything short of loadtest, security and e2e-test.   in regards to loadtest, you're absolutely right.  the idea is that, in general (esp. for things like minor releases), we need a loadtest that can act like a smoke test to verify that service functions as expected at the api level and can handle load.  obviously for things like newer products, major releases or instance sizing, we'd probably want to continue to do loadtesting manually.

**Comment by rpappalax** [comment]
@stuartphilp also mentioned adding 1 more test type: [security] to the test manifests for once we start writing zap tests.

**Pull request merged**
