### PR TITLE
Initial commit of config-check tests

### PR DESCRIPTION
**Pull request by chartjes**
These tests are making sure that content stored in Kinto has the correct signatures and then reports results to Testrail.

r? @karlht

### CODE REVIEW

**Comment by karlht** [comment]
Typo in the README:  "To tun the tests" should probably read "To run the tests"

**Comment by karlht** [comment]
I'd like to see a little more detail/documentation on what the `@testrail` decorator does, and how.

**Comment by chartjes** [comment]
@karlht r? I expanded the details about the Testrail integration, please take a look

**Comment by karlht** [comment]
This looks good to me, but github is indicating that there are conflicts ... I'll be glad to merge once the conflicts are resolved.

**Pull request merged**
