### PR TITLE
Collection modification and signing test

### PR DESCRIPTION
**Pull request by chartjes**
r? @karlht

### CODE REVIEW

**Comment by karlht** [comment]
I am on PTO today but will review this tomorrow.

**Comment by karlht** [comment]
Chris, do you want to leave this history expanded or squash to one commit?   I notice that there's a "chore" marker in your commit log -- are you using something to pull those commit logs into a  changelog, and I'm not seeing it?

**Comment by chartjes** [comment]
@karlht Let's leave the history in there -- I am not a fan of squashing commits.

As for the "chore" marker, I am not using anything that pulls these into a changelog so I'm not sure what you might be referring to

**Comment by karlht** [comment]
I was thinking of something like https://github.com/lob/generate-changelog -- where particular markers in commit logs generate changelog entries.

I am definitely ok with not squashing.

This looks good -- the only improvement I would suggest in the future would be a short paragraph's worth of explanation (in a changelog or elsewhere) of why all of these commits belong together in one collection/bundle of changes.

r+ and merging.

**Pull request merged**
