### PR TITLE
Loop server config check

### PR DESCRIPTION
**Pull request by chartjes**
Added in the library requirements and configuration checking scripts that I use for Loop client deployments.

r? @rpappalax

### CODE REVIEW

**Comment by rpappalax** [comment]
are you using same script for both loop-server & loop-client?  if that's the case, i'm wondering if it wouldn't be better to put it in:  /services-test/loop instead

**Comment by chartjes** [comment]
That would be a good idea now that I think of it.

**Comment by rpappalax** [comment]
it could prob go the same way, something like:  services-test/loop/config-check
not sure from a run file perspective how tests in here would get executed for loop-client or loop-server, but we could look at that later.  putting the code in here would at least prevent duplication

**Comment by chartjes** [comment]
Yeah, I will fix the PR and move those files over there.

**Comment by rpappalax** [comment]
+1

**Pull request merged**
