### PR TITLE
Starting Page Object Model in JS

### PR DESCRIPTION
**Pull request by cuff-links**

### CODE REVIEW

**Comment by pdehaan** [comment]
@silne30 Thanks so much for hacking on this with me today! This is awesome, and will make it so much easier to share some marionette code between our Pocket and Hello tests.

**Comment by cuff-links** [comment]
@pdehaan My pleasure, man. Definitely was fun. We will get together next week and crack at it some more.

**Comment by rpappalax** [comment]
looks like for desktop FF we're not going to be using Marionette JS, but since we will be creating the occasional B2G test, can we still make use of this?  (aka: should we merge this)?
@Silne30? @pdehaan?

**Comment by stuartphilp** [comment]
abstracted into a mjs pom helper maybe? i think the pocket test should be rewritten in python

**Comment by pdehaan** [comment]
I think this can be closed and rot quietly in the corner. It will still be around if we need it, but yeah, we should port all these to Python for desktop stuffs and only use Marionette JS for B2G related things.

**Pull request closed without merging**
